#!/usr/bin/env python3

from rich import print
from pathlib import Path
import shutil
import sys

source = Path("~/Informative-theme/info_theme.toml")
destination = Path.home() / ".config" / "starship.toml"

print("[red][underline]Read Warning:[/][/]")
print("[red]This will overwrite your Starship config.[/]")

if input("Proceed? [yes/no]: ").lower() != "yes":
    print("Program exited.")
    sys.exit()

destination.parent.mkdir(parents=True, exist_ok=True)

shutil.copy(source, destination)

print("[green]Theme copied successfully![/]")